! BEGIN DART PREPROCESS TYPE DEFINITIONS
!SNOW_DEPTH,                     QTY_SNOW_DEPTH,  COMMON_CODE
!SNOW_WATER_EQUIVALENT,          QTY_SNOW_WATER,  COMMON_CODE
! END DART PREPROCESS TYPE DEFINITIONS
